<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\MyStudents.Domain\MyStudents.Domain.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="FluentValidation" Version="*" />
    <PackageReference Include="FluentValidation.DependencyInjectionExtensions" Version="*" />
    <PackageReference Include="MediatR" Version="*" />
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="*" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
